#!/bin/bash

HOST="mafreebox.freebox.fr"
VERSION="0.1"

UA="Fbx SNMP Stats v${VERSION}"
C=$(which curl)
CURL="${C} -s -4 -A ${UA}"

[ ! -x ${C} ] && { echo "Curl is not installed."; exit 1; }

fbx_version() {
  ${CURL} http://${HOST}/api_version
}

case $1 in
  version)
    fbx_version
    ;;
  *)
    echo "Not implemented."
    ;;
esac
