#!/bin/bash
### TODO
###
### check variables for $0 login
###
###

HOST="mafreebox.freebox.fr"
VERSION="0.1"
CONF="${HOME}/.freeboxsnmp"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
UA="Fbx SNMP Stats v${VERSION}"
C=$(which curl)
CURL="${C} -s -4 -A ${UA}"
API="${DIR}/lib/freeboxos-bash-api/freeboxos_bash_api.sh"

[ ! -x ${C} ] && { echo "Curl is not installed."; exit 1; }
[ -e ${API} ] && source ${API} || { echo "API is not present."; exit 2; }

# Conf management
_reset_conf() {
  echo "APP_NAME=\"fr.freebox.hebeo.snmp\"
APP_FULL_NAME=\"Freebox OS SNMP Bash interface\"
APP_VERSION="${VERSION}"
APP_OS=$(HOSTNAME)
APP_ID=\"fr.freebox.hebeo.snmp\"
APP_TOKEN=" >${CONF}
}
_save_conf() {
  echo "APP_NAME=\"fr.freebox.hebeo.snmp\"
APP_FULL_NAME=\"Freebox OS SNMP Bash interface\"
APP_VERSION=\"${VERSION}\"
APP_OS=\"$(HOSTNAME)\"
APP_ID=\"fr.freebox.hebeo.snmp\"
APP_TOKEN=\"${APP_TOKEN}\"" >${CONF}
}

[ ! -e ${CONF} ] && { touch ${CONF}; _reset_conf; }
source ${CONF}

if [ "z$APP_ID" == "z" ]; then
  if [ $# -eq 0 ]; then
    echo "You need to call \"$0 auth\"  to initiate App Authorization."
    exit 4
  else
    if [ $1 == "login" ]; then
      # We don't exit if we call login
      echo "" >/dev/null
    elif [ $1 == "auth" ]; then
      # We don't exit if we call auth
      echo "" >/dev/null
    else
      echo "You need to call \"$0 auth\"  to initiate App Authorization."
      exit 8
fi; fi; fi

### Calls

### Main Loop
case $1 in
  version)
    echo ${_API_VERSION}
    ;;
  auth)
    authorize_application ${APP_NAME} "${APP_FULL_NAME}" ${APP_VERSION} ${APP_OS}
    echo "Call \"$0 login MY_APP_TOKEN\" to first log application in the FreeBOX.";;
  login)
    APP_TOKEN=$2
    _save_conf
    answer=$(call_freebox_api /login/)
    challenge=$(get_json_value_for_key "${answer}" "result.challenge")
    salt=$(get_json_value_for_key "${answer}" "result.password_salt")
    password=$(echo -n "$challenge" | openssl dgst -sha1 -hmac "$APP_TOKEN" | sed  's/^(stdin)= //')
    echo "$challenge / $APP_TOKEN / $password"
    ;;

  chk_login)
    answer=$(call_freebox_api /login/)
    [ $(get_json_value_for_key "${answer}" "result.logged_in") == "true" ] && echo "We are logged in." || echo "We are not logged in.";;
  *)
    echo "Not implemented."
    ;;
esac
