#!/bin/bash

HOST="mafreebox.freebox.fr"
VERSION="0.1"

UA="Fbx SNMP Stats v${VERSION}"
C=$(which curl)
CURL="${C} -s -4 -A ${UA}"

case $(uname) in
  Darwin)
    OS="Mac OSX";;
  Linux)
    OS="Linux";;
  FreeBSD)
    OS="FreeBSD";;
  *)
    OS="Unknown";;
esac

[ ! -x ${C} ] && { echo "Curl is not installed."; exit 1; }

__END__
}

case $1 in
  version)
    echo ${_API_VERSION}
    ;;
  *)
    echo "Not implemented."
    ;;
esac
